### ISSUE TITLE
Being able to disable/replace ZSH Pokemon-colorscripts

### ISSUE THREAD

**Issue by Hisui02** [richen604/hydenix#12]
## Feature Description
Being able to disable/replace ZSH Pokemon-colorscripts

## Problem Statement
I'm not a huge pokemon fan and I would prefer to launch a fastfetch on the terminal opening.

In hyprdots (Arch) you can directly edit .zshrc, but here it's being created and references to some nix-profile files.

## Proposed Solution
Add a variable in config.nix that contains
``bash
#Display Pokemonks
pokemon-colorscripts --no-title -r 1-3
``

but can be replaced with and empty string (do nothing) or a custom command (like fastfetch)

## Checklist
- [X] I have checked for existing feature requests
- [X] I have provided clear use cases
- [X] I have explained the value this feature would add

**Comment by Hisui02** [comment]
Thank you, I was able to disable the Pokemons, but they can't be replaced with a fastfetch because the syntax higlight gets activated at the last line so my fastfetch gets completely white.

```zsh
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh  

source $HOME/.local/state/nix/profiles/home-manager/home-path/share/hyde/hyde-cli/shell-completions/Hyde.zsh

export PATH=$HOME/.local/bin:$PATH

alias ff='fastfetch'
alias e='exit'
alias rebuild='sudo nixos-rebuild switch --flake ~/hydenix/#hydenix'

alias cat='bat'

alias ga='git add .'
alias gc='git commit -m'
alias gp='git push'


fastfetch # <-- WHERE MY FASTFETCH ENDS

source /nix/store/s8pf5chrgrfxpn0p4lgrlxsb3x4nfg6a-nix-index-with-db-0.1.8/etc/profile.d/command-not-found.sh


# Aliases


# Named Directory Hashes


source /nix/store/f1nbdis12xsfglc33sif4cakvfypxybf-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS+=() # <-- HERE
```

Here is my nix zsh module

```nix
{lib, ... }:
{
  programs.zsh = {
    # TODO: Disable Pokemons and replace by fastfetch

    initExtraFirst = lib.mkForce ''
      #Display Pokemonks
      #pokemon-colorscripts --no-title -r 1-3
      # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
      # Initialization code that may require console input (password prompts, [y/n]
      # confirmations, etc.) must go above this block; everything else may go below.
      if [[ -r "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh" ]]; then
        source "''${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-''${(%):-%n}.zsh"
      fi
    '';
    initExtra = ''
        alias ff='fastfetch'
        alias e='exit'
        alias rebuild='sudo nixos-rebuild switch --flake ~/hydenix/#hydenix'

        alias cat='bat'

        alias ga='git add .'
        alias gc='git commit -m'
        alias gp='git push'


        fastfetch
    '';

    # initExtraBeforeCompInit = ''
    #     fastfetch
    # '';
  };
}

```

**Comment by richen604** [comment]
try `zsh.syntaxHighlighting.enable = lib.mkForce false;`

its possible to install this as a ohmyzsh plugin and that may get around the sourcing order if you still want it

you can of course mkforce false all of the zsh hm config and use `home.file` force enabled for your own `.zshrc`

having it mutable isnt recommended. 
nixos and hm reruns scripts on relog/reboot/rebuild so edits will be gone. thats why it's not done this way by default as `.zshrc` is commonly edited

**Comment by goodmorning-hwt** [comment]
Is it possible to disable p10k?   I can replace the `initExtraFirst`, however for the `initExtra` it was spliced together instead of my config override the original.

**Comment by richen604** [comment]
> Is it possible to disable p10k?   I can replace the `initExtraFirst`, however for the `initExtra` it was spliced together instead of my config override the original.
> 
> 

use nix `lib.mkForce` to overwrite options

honestly if you want a custom config youre better off just forking the repo
