### ISSUE TITLE
[FEATURE] Support for nixos aarch64

### ISSUE THREAD

**Issue by CrypticEntity** [richen604/hydenix#14]
I'm relatively new to nixos so I'm not sure how challenging this would be to implent.

**Comment by richen604** [comment]
change system variable in the template flake and try running the vm.
im not sure what is required package wise to provide support so ymmv
does HyDE by default support arm?

**Comment by CrypticEntity** [comment]
Arch for arm is pretty small project so I imagine you would run into issues.

`hypr@nixos ~/hydenix (master) [1]> nix run . 
warning: Git tree '/home/hypr/hydenix' is dirty
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:34:12:
           33|
           34|   strict = derivationStrict drvAttrs;
             |            ^
           35|

       … while evaluating derivation 'nixos-vm'
         whose name attribute is located at /nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/pkgs/stdenv/generic/make-derivation.nix:336:7

       … while evaluating attribute 'buildCommand' of derivation 'nixos-vm'
         at /nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/pkgs/build-support/trivial-builders/default.nix:59:17:
           58|         enableParallelBuilding = true;
           59|         inherit buildCommand name;
             |                 ^
           60|         passAsFile = [ "buildCommand" ]

       … while evaluating the option `virtualisation.vmVariant.system.build.toplevel':

       … while evaluating definitions from `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/nixos/modules/system/activation/top-level.nix':

       … while evaluating the option `virtualisation.vmVariant.warnings':

       … while evaluating definitions from `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/nixos/modules/system/boot/systemd.nix':

       … while evaluating the option `virtualisation.vmVariant.systemd.services.home-manager-hydenix.serviceConfig':

       … while evaluating definitions from `/nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/flake.nix':

       … while evaluating the option `virtualisation.vmVariant.home-manager.users.hydenix.home.activation.mutableFileGeneration.data':

       … while evaluating definitions from `/nix/store/ss1rcnzpgy5mrlg1i253km60m1wlprvw-source/hydenix/hm/mutable/mutable.nix':

       … while evaluating the option `virtualisation.vmVariant.home-manager.users.hydenix.home.file.".config/Kvantum/wallbash/wallbash.kvconfig".source':

       … while evaluating definitions from `/nix/store/ss1rcnzpgy5mrlg1i253km60m1wlprvw-source/hydenix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: a 'x86_64-linux' with features {} is required to build '/nix/store/lgx1fm2v15fkl6k4d1la8sqm5nqs0gdg-Frosted-Glass.drv', but I am a 'aarch64-linux' with features {benchmark, big-parallel, gccarch-armv8-a, kvm, nixos-test}`


The other themes produce the same error.

**Comment by richen604** [comment]
since HyDE does not have arm support that i know of it would require too much deviation to attempt to support it. 

you are more than welcome to attempt to tackle this yourself as a fork
