### ISSUE TITLE
[BUG] nixos-system no such file or direcotry

### ISSUE THREAD

**Issue by ShadowRa88it** [richen604/hydenix#15]
## Bug Description
I will preface that I am new to nixOS and hydenix. Receiving an error when trying to run `nix run .#hydenix`

## Steps to Reproduce
1. New nixOS VM with basic config.
2. nix flake nit -t github:richen604/hydenix
3. nix run .#hydenix
4. 

## Expected Behavior
No errors and then switch the system

## Actual Behavior
I receive an error:
![image](https://github.com/user-attachments/assets/d6a8d443-6033-470a-967f-4fad947acf60)
-t
## System Information
<details>
<summary>System Details</summary>

```bash
# Please paste the output of:
nix-shell -p nix-info --run "nix-info -m"
```
![image](https://github.com/user-attachments/assets/cea1fd88-aea6-47af-8817-282a060d3ca7)

</details>

<details>
<summary>System Logs</summary>

```bash
# Please paste relevant logs from:
journalctl -b                                           # System logs
journalctl --user -b                                   # User logs

sudo systemctl status home-manager-$HOSTNAME.service   # Home-manager status
```
No relevant journalctl logs
Doesn't make it far enough to get home-manager running
</details>

## Configuration

https://github.com/ShadowRa88it/hydenix/tree/main

## Environment
- [ X] NixOS VM
- [ X] Templated Flake
- [ ] Cross-distro VM (specify: Arch/Fedora)
- [ ] Other (please specify)

## Checklist
- [ ] I have checked for existing issues
- [ ] I have included all relevant system information
- [ ] I have included relevant logs
- [ ] I have provided my configuration

**Comment by AdrienLemaire** [comment]
Same here, new nixos/hyprland user.
Getting the same user as @ShadowRa88it.
`nix run github:richen604/hydenix` starts a VM which works fine.
When trying to apply the conf system-wide, I also have this error:
```console
[dori@xps13-9320:~/Projects/Perso/hydenix]$ sudo nixos-rebuild test --flake .#hydenix
warning: Git tree '/home/dori/Projects/Perso/hydenix' is dirty
error: flake 'git+file:///home/dori/Projects/Perso/hydenix' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."hydenix".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."hydenix".config.system.build.nixos-rebuild' or 'nixosConfigurations."hydenix".config.system.build.nixos-rebuild'
```

**Comment by richen604** [comment]
this is by design, you should not be running this config directly.

follow the template flake installation steps

**Comment by richen604** [comment]
@ShadowRa88it 
`nixosvm` is your hostname 
`sudo nixos-rebuild switch --flake .` or `sudo nixos-rebuild switch --flake .#nixosvm`

**Comment by ShadowRa88it** [comment]
That did it thank you very much

**Comment by AdrienLemaire** [comment]
Thanks @richen604, looks great!

I'm a bit confused, probably a newbie misunderstanding. Now that hydenix is applied system-wide, I have lost google-chrome, and I don't understand how to readd it. 
My files in /etc/nixos/ have not been replaced, and seem useless now.
Looks like everything must be setup in the hydenix repo now.

In `config.nix`, I have added:
```nix
nixpkgs.config.allowUnfree = true;
nixModules = [
  (toString ./my-module.nix)
];
```
Then I created `my-module.nix`
```nix
{config, pkgs, ...};
{
  environment.systemPackages = with pkgs; [
    google-chrome
  ];
}
```

But I get this error:
<details><summary>sudo nixos-rebuild switch --flake .</summary>
<p>
❯ sudo nixos-rebuild switch --flake .
warning: Git tree '/home/dori/Projects/Perso/hydenix' is dirty
error:
       … while calling the 'seq' builtin
         at /nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/lib/modules.nix:334:18:
          333|         options = checked options;
          334|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          335|         _module = checked (config._module);

       … while evaluating a branch condition
         at /nix/store/lsy6c2f9alj2gkjj36h754kk63x6701l-source/lib/modules.nix:273:9:
          272|       checkUnmatched =
          273|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |         ^
          274|           let

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: path '/nix/store/rvk6yacbgg2f2pwc8hhnj6x0z4d50zs5-source/my-module.nix' does not exist
</p>
</details> 
It's complaining because `my-module.nix` doesn't exists in a nix/store source :thinking:

**Comment by richen604** [comment]
`git add .` will fix your module issue. flakes with git require files in staging

**Comment by AdrienLemaire** [comment]
Many thanks !
